### ISSUE TITLE
No mention in gocd configuration documentation

### ISSUE THREAD

**Issue by t0il3ts0ap** [gocd-contrib/script-executor-task#42]
I dont see `<script>` or `<scriptExecutor>` tag [here](https://docs.gocd.org/current/configuration/configuration_reference.html).

My aim is to use this feature in a template which I am configuring via cruise-config.xml

**Comment by chadlwilson** [comment]
This is very outdated, so perhaps not relevant now, but the missing note re: cruise config is because this is a plugin and plugins can define their own required config values - the documentation there only refers to base level configuration, so it would be under https://docs.gocd.org/current/configuration/configuration_reference.html#pluginConfiguration

Nevertheless, the canonical way to use this plugin most cleanly to template pipelines would be by use of config repos, and the YAML, JSON or Groovy plugins for doing so, rather than via GoCD server config. The YAML plugin has shorthand syntax specifically supporting this plugin, as documented [here](https://github.com/tomzo/gocd-yaml-config-plugin#script)
